### ISSUE TITLE
Воздух в трубах сжигателя

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#105]
Репорт от игрока Sreb#2329.

По дефолту в трубах сжигателя есть воздух, который мешает подбирать правильные пропорции.

**Comment by ITCups** [comment]
Какой сжигатель, в диспозал ?
какие там могут быть пропорции ?

**Comment by Epicus7** [comment]
Я так понимаю, имеется в виду газовая камера в научном.
