### ISSUE TITLE
Маленькая буква в одном из атак-логов

### ISSUE THREAD

**Issue by Archemagus** [Rampoch/Chaotic-Onyx#111]
![image](https://user-images.githubusercontent.com/32466328/39100015-1749255e-468c-11e8-947b-333d1593c93b.png)
Типа я дафно не был, фсе дела, но думаю на опухе не любят мелкобукфие.

P.S. У меня сломалась эта клафиша, но мне лень открыфать экранную клафиатуру. Короче интересно у фас, посмотрим куда дальше будете разфифаться.

**Comment by ITCups** [comment]
починил в #139
