### ISSUE TITLE
Сломанная труба в токсинах

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#113]
Возможно, это не со старта было и все нормально.

![image](https://user-images.githubusercontent.com/5204667/39155534-119b5f4e-475b-11e8-839b-ddff2c1e1c3d.png)

**Comment by Doloreere** [comment]
![image](https://user-images.githubusercontent.com/22078308/39544616-49977290-4e57-11e8-9f4d-86c4d331ed20.png)
