### ISSUE TITLE
Улучшение роботехники

### ISSUE THREAD

**Issue by ITCups** [Rampoch/Chaotic-Onyx#129]
#### Описание идеи

- Мало место в роботехе.
- Спрайты инструментов Retractor и Hemostat хреновые. 
- Станция экстренного сброса модуля для боргов

#### Дополнительная информация
Хотел бы урезать коморку для зарядки и впилить туда хирургическую как на ТГ.Добавить столов в основную... Идеи чем занять место приветствуются...
Сделать кабинет удобным. Бывают случаи когда трупы идут потоком и вокруг хирургического стола затор. Некуда складывать трупы (таскать до меда так себе вариант и тащить в морг IPC'шников как то неправильно).

Добавить контур спрайтам инструментов (возможно сделать больше). Приходится тыкать турф

Без роботеха боргам тяжко и играть боргом без цели так себе занятие. Моя идея добавить станцию для сброса модуля в коморку в для киборгов под мостиком. Спамить сброс не получиться (ограничение по использованию (в виде ресурсов или времени) плюс аннонс в чат при использовании) Открыто для критики и обсуждения...

- [ ] Проблему можно воспроизвести хотя бы один раз
- [ ] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [ ] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [ ] Проблема случилась в недавнем раунде (прошло меньше недели)
- [x] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by Epicus7** [comment]
IPC сейчас отключены и не факт, что мы будем их включать.

Все остальное - можешь сделать, почему нет. Перепилить кабинет робототехника - не то чтобы что-то критичное. 

Станцию для смены модуля киборга тоже можно добавить, но я бы сделал там куллдаун, например, один раз в пол часа. Или что-то в этом духе. Плюс не уверен, что стоит пилить ее отдельно - можно встроить эту функцию в станцию подзарядки, но с общим куллдауном.

**Comment by Epicus7** [comment]
cb44c51d3d5fc2b9e21b50192c4733202f859f48
