### ISSUE TITLE
Эммитер в двигателе питается от общего SMESa

### ISSUE THREAD

**Issue by ITCups** [Rampoch/Chaotic-Onyx#130]
#### Описание проблемы
Эммитер в инженерной питается от общего SMESa.

#### Разница между реальным поведением и ожидаемым
Очевидно чтобы запитать генератор нужно электричество но на станции бывает что его нету.
Добавить смес на нижний уровень под двигателем специально для него.( Да , жирно... но так будет проще) 

#### Как воспроизвести проблему?
Запитайте эммитер с пустым смесом...

#### Дополнительная информация

- [х] Проблему можно воспроизвести хотя бы один раз
- [х] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [х] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [х] Проблема случилась в недавнем раунде (прошло меньше недели)
- [х] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by Epicus7** [comment]
Ну какая-то странная идея делать целый СМЕС под один эммитер

**Comment by ITCups** [comment]
можно АПЦ в комнате питать от него

**Comment by Epicus7** [comment]
Вообще эммитер должен питаться от APC, а APC от SMES. Если у тебя кончилась энергия - меняешь батарейку и профит. Не вижу проблем.
