### ISSUE TITLE
Баги карты в РНД

### ISSUE THREAD

**Issue by ITCups** [Rampoch/Chaotic-Onyx#135]
#### Описание проблемы
Баги карты в РНД. 

- В Токсинах нету терминала пожарной тревоги,на полу валяется отвертка и гаечных ключ.
- У РД нету пожарного шаттера
- В ксенобиологии нету пожарного шаттера и терминал тревоги находиться в недоступном месте , за ящиком

**Comment by ghost** [comment]
Ты про этот? К нему можно пробраться открыв ящик. 
А вот шаттеров нет это да.
![image](https://user-images.githubusercontent.com/29167103/39852753-f1a52fa2-5426-11e8-8664-85eb863a4e06.png)

**Comment by ITCups** [comment]
да этот, но тем не менее он неправельно сделан.Он находится в стене а должен на полу перед ней (как бы странно это не звучало), как на всей станции

**Comment by ITCups** [comment]
в крайнем случае его можно подвинуть к скраберу

**Comment by ITCups** [comment]
я проверил , он расположен правельно на полу...

**Comment by ghost** [comment]
Окей, я починю.

**Comment by ITCups** [comment]
я уже сделал не парься

**Comment by ITCups** [comment]
Починил вместе с новым роботехом

**Comment by Epicus7** [comment]
Починили здесь: 72ef08d2e4e3b95ebe0931faa2efa763f54d6ae0
