### ISSUE TITLE
Отсутствие спрайта flannel shirt.

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [Rampoch/Chaotic-Onyx#137]
#### Описание проблемы
Отсутствие спрайта flannel shirt.

#### Разница между реальным поведением и ожидаемым
Присутствие спрайта flannel shirt.

#### Как воспроизвести проблему?
Надеть flannel shirt любой расцветки.

#### Конкретная информация
 Просто берёт и отсутствует спрайт flannel shirt на персонаже.

#### Как долго известно о проблеме?
Просто берёт и отсутствует спрайт flannel shirt на персонаже.

#### Версия клиента, версия сервера и идентификатор игры
Beta.  bUh-dnMw. 122191845972c2c247f80d088d1debffc7a1dfe3 - dev - 2018-05-06.

#### Дополнительная информация

- [x] Проблему можно воспроизвести хотя бы один раз
- [x] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [x] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [x] Проблема случилась в недавнем раунде (прошло меньше недели)
- [x] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by n0rm4ld3f4ult** [comment]
А ещё половины штанов тоже.

**Comment by Epicus7** [comment]
Уже все должно работать после
fc3e4c981e6b08778f7266492ba209133333f6fa
76a8044691b88933575a3536e17c6ac8f9d72115
