### ISSUE TITLE
Мердж тайлов с Torch'a , Корридоры нового цвета на станции

### ISSUE THREAD

**Issue by ITCups** [Rampoch/Chaotic-Onyx#147]
#### Описание предложения
При попытке мерджа файлов турфа с Torch'a , по умолчанию встали коридоры сероголубого цвета.
В этих файлах есть немало новых стилей пола и украшений для пола.
Серый цвет могу вернуть по дефолту

как вам идея нового цвета коридоров ?
![default](https://user-images.githubusercontent.com/6437377/39976895-7bb6be7c-5760-11e8-8203-624a33855269.png)
![default](https://user-images.githubusercontent.com/6437377/39976905-8a1eafa6-5760-11e8-9eea-9f6efd039fb6.png)
![default](https://user-images.githubusercontent.com/6437377/39976959-f6c9ab88-5760-11e8-84b5-8dab89247174.png)
![default](https://user-images.githubusercontent.com/6437377/39976968-ff1be0da-5760-11e8-88fe-ae450b9de3b6.png)
![default](https://user-images.githubusercontent.com/6437377/39976995-1df615b6-5761-11e8-8db8-4506a697da71.png)
![default](https://user-images.githubusercontent.com/6437377/39977004-295bb33e-5761-11e8-9476-0234673282ae.png)
![default](https://user-images.githubusercontent.com/6437377/39977020-404fdaa2-5761-11e8-8bbc-fb7de204f5d0.png)

**Comment by Epicus7** [comment]
Даже не знаю. Я думаю, что Торч должен оставаться на Торче, а Эрис на Эрисе.

От перетаскивания спрайтов лишние ассоциации будут появляться.
