### ISSUE TITLE
Карпы не наносят урон

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#156]

**Comment by ITCups** [comment]
![default](https://user-images.githubusercontent.com/6437377/40459678-f32408e2-5f2c-11e8-90e9-0f6a5c44a5f9.png)
как я тестил наносят , станят, вводят в крит

**Comment by ITCups** [comment]
в скафандрах тоже тестил правда не во всех

**Comment by Epicus7** [comment]
Ну значит будем считать, что не воспроизводится.
