### ISSUE TITLE
А где водород на карте?

### ISSUE THREAD

**Issue by Voldirs** [Rampoch/Chaotic-Onyx#17]
На бэе относительно недавно появился водород, вроде как на замену форону. Будет ли он использоваться в атмосе или ну его нафиг?
Я глянул в коде, в принципе, этот газ не особо то и нужен кроме как для двигателя, где его вполне заменяет форон, а ещё водород внезапно нужен для огнемёта. И вроде его можно использовать для создания двубалонок.

**Comment by Epicus7** [comment]
Надо смотреть код, читать вики - разбираться что там и как. Посмотрим, короче

**Comment by Epicus7** [comment]
Добавили водород в атмосферный отсек: (72ef08d2e4e3b95ebe0931faa2efa763f54d6ae0)
