### ISSUE TITLE
Мелкобаги с расами

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#179]
- [x] Нужен нормальный дефолтный цвет всем расам, который будет включатся при ее выборе. Сейчас, например, у Унати он черный и их не видно на заднем фоне.
- [x] Походу у Унати рисуется второй слой глаз, оставшийся с Бейского варианта.
- [x] Расам нужно включить их языки по дефолту.
- [x] Добавить джоббаны на расы.
- [x] Автохисс починить.

**Comment by ITCups** [comment]
еще вот это но не так важно
![default](https://user-images.githubusercontent.com/6437377/40548274-73bd8afa-605e-11e8-94b6-15ea55e4904e.png)
я тут один
походу костюм или тело рисуется с отступом

**Comment by ITCups** [comment]
по дефолту нужно языки впихивать расовские

**Comment by Epicus7** [comment]
Это только у госта так рисует, @LagannPM?

**Comment by ITCups** [comment]
Видел только у госта пока что

**Comment by ITCups** [comment]
У самцов рас надеты лифчики
![default](https://user-images.githubusercontent.com/6437377/40557378-14b531d6-607a-11e8-99dd-0d299449c034.png)

**Comment by Epicus7** [comment]
Первые три бага починил: 9edd854ceb3d919157bde921d67f88dcca66fe47

**Comment by Epicus7** [comment]
Насчет костюма - недостаточно информации, хз я что там случилось. Раса может быть тут даже не причем. А лифчики можно одеть и на человека мужского пола. Тут вопрос в том, что при смене расы не ставится дефолтное нижнее белье.

**Comment by Epicus7** [comment]
Все починил.
Джоббаны: d7ce83d31fc159f507c56cfaf31531c0601bdc0d
Автохисс: 95887eff06e61db875953bda57a8ad1b1d6e4a34
