### ISSUE TITLE
Доставать оружие из Holster'а нажатием ЛКМ

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#18]
На БлюБее так работало. Сейчас же надо лезть в меню через ПКМ, что долго и неудобно.

Тоже самое желательно сделать с ножами в jackboots.

**Comment by Voldirs** [comment]
С кобурами так не получится банально по одной причине, на новобэе можно прицепить одновременно и разгрузку, и кобуру. И при клике открывается именно разгрузка. А с ножом в сапогах вроде и так работает нормально.

**Comment by Epicus7** [comment]
А если только кобуру прикрепить?

**Comment by Voldirs** [comment]
Не проверял

**Comment by ghost** [comment]
Если только кобуру, то нельзя, всё-равно либо через горячие клавиши, либо через контекстное меню

**Comment by Epicus7** [comment]
Только с кобурой не работало.

Короче теперь щелчок пустой рукой активирует самый верхний (последний надетый) аксессуар. С кобурой тоже работает, да.
Щелчок предметом активирует сразу все, но на практике находит только одно место, куда воткнуться.
