### ISSUE TITLE
Глаза Унати кривые, или нет ?

### ISSUE THREAD

**Issue by ITCups** [Rampoch/Chaotic-Onyx#181]
![default](https://user-images.githubusercontent.com/6437377/40545695-e91d72ea-6056-11e8-8185-736b05c9bdcf.png)
![default](https://user-images.githubusercontent.com/6437377/40545705-f21be4ee-6056-11e8-9a89-f77031a1a2b4.png)

**Comment by Epicus7** [comment]
Дублирует #179
