### ISSUE TITLE
Добавить пианино в бар

### ISSUE THREAD

**Issue by GusevDuhast** [Rampoch/Chaotic-Onyx#196]
У нас был апгрейд кол-ва строк для музыкальных инструментов, но самих инструментов нет. Логичней всего было бы добавить тоже самое пианино в бар, дабы люди могли решать, или музыку из автомата слушать, или же играть ее самим. Да и вам проще будет добавить его официально, а не спавнить каждый раунд

**Comment by Epicus7** [comment]
Сделали: 56357e1e70f04e4d5558fe1ff298b69ed6909a6d
