### ISSUE TITLE
Подогнать штрафы в Space Law под экономику в билде

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#20]
Пачка сигарет стоит 100 талеров, а штраф за побег - 500. Не порядок.

**Comment by Voldirs** [comment]
Тут надо смотреть сколько среднее количество денюжек у среднестатистического хумана по коду, а не стоимость сигарет.

**Comment by Epicus7** [comment]
Обычные сигареты стоят не 100, а 45, если верить тому, что вижу в коде.

Формула для стартовой зарплаты довольно унылая и по ней хрен прикинешь - там куча разных модификаторов и получаются зарплаты от, практически, нуля, до десятков тысяч.

Фактически, говорят, что у ассистента стартовый счет обычно меньше сотни, а у нормальных людей редко доходит до 1500.

Если все так, то штрафы нормальные - ничего менять не надо.
