### ISSUE TITLE
Перенести печень из задницы в тело

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#220]
Сейчас чтобы достать печень, нужно оперировать зону паха, а не тело, что противоречит вики и здравому смыслу.

**Comment by alexv-ds** [comment]
Внезапно печень и находится ближе к паху, ближе чем все остальное.

**Comment by ZerlGray** [comment]
Вот кстати с человеком выше согласен. Противоречит здравому смыслу как раз то, что печень в... торсе.

**Comment by Vostok-Odin** [comment]
![pechen](https://user-images.githubusercontent.com/38241773/42421375-2cd9c634-82dd-11e8-9554-6fe83fdb04aa.jpg)

**Comment by ZerlGray** [comment]
по моему, это ближе к жопе, чем к туловищу

**Comment by Epicus7** [comment]
Все-таки, если посмотреть на разбиение куклы, и на эту картинку выше, то печень оказывается в торсе, а не в пахе.
