### ISSUE TITLE
Неплохо бы перевести фразочки персонажей при принятии лсд на русский язык.

### ISSUE THREAD

**Issue by Voldirs** [Rampoch/Chaotic-Onyx#25]
Чтобы понять о чём я, попробуйте на сервере принять лсдшку и постоять в толпе людей. А ещё помимо перевода можно докинуть каких-нибудь мемов.

**Comment by Epicus7** [comment]
Ну там еще есть всякие эмоции, синдром Туррета, если им можно заболеть и прочие вещи, которые тоже можно перевести.
