### ISSUE TITLE
Трапы и недостающий орган.

### ISSUE THREAD

**Issue by ghost** [Rampoch/Chaotic-Onyx#261]
У трапов нету матки, это как-то объясняется лором? За 500 лет человечество научилось плодиться более продвинутым путём? Не годится.
У трапов должен быть свой орган.

**Comment by Vostok-Odin** [comment]
В таком случае я требую всем белым мужчинам за тридцать личный рояль.

**Comment by ZerlGray** [comment]
И член мужчинам. Чтобы симбирский мог его отрезать.........................................

**Comment by Epicus7** [comment]
Это фича.
