### ISSUE TITLE
Насколько я понял, паучки теперь не вырастают в гигантских пауков. Разнерфить бы.

### ISSUE THREAD

**Issue by Voldirs** [Rampoch/Chaotic-Onyx#28]

**Comment by Epicus7** [comment]
Не знаю о каких пауках ты говоришь - смотреть надо.

Вроде, раньше был ивент, в ходе которого в каком-то отсеке спавнились уже большие пауки сразу. Но маленькие, вырастающие в больших?

**Comment by Voldirs** [comment]
При этом эвенте спаунились как раз маленькие паучки, которые по вентиляции пробирались в рандомные точки карты и там вырастали до гигантских

**Comment by Voldirs** [comment]
Всё работает, можно закрыть
