### ISSUE TITLE
Победа культа засчитывается всегда.

### ISSUE THREAD

**Issue by ghost** [Rampoch/Chaotic-Onyx#284]
У Культистов есть такая задачка, как выжить в некотором числе и добраться до ЦК на эскейп поде или же шаттле. Но она работает некорректно, из-за чего игра считает, что на ЦК приходит нужное число культистов, хотя это не так.

Есть подозрение что весь код с победой культистов сломан.

**Comment by Rodial-Admiral** [comment]
Я тут посмотрел кусок кода, который за это отвечает. Случайно.
В общем, вот:
`if(acolytes_survived >= target_amount)
		return 0
	else
		return 1`
Живите с этим.

**Comment by Rodial-Admiral** [comment]
Пы Эс:
С надеждой на то, что единичка означает выполнение цели, а нолик - невыполнение, работает это видимо так:
Сейчас оно засчитывает цель, если в неком наборе зон (шаттл и поды подразумеваются) находится МЕНЬШЕ пяти живых культистов, вроде как не в крите.

**Comment by Rodial-Admiral** [comment]
btw случайный заход в objective.dm показал, что там далеко не только эта задача сломана.
Например, чудесный код проверки задачи на убийство глав у революционеров.

**Comment by Rodial-Admiral** [comment]
В общем, я бы предложил людям, которые это фиксят, заменить левую проверку на "защищенные зоны после эвакуации" на те вещи, которые есть в том же .dm-файле, функция datum/objective/block для поехавших синтетиков.

**Comment by Rodial-Admiral** [comment]
Т.е. сейчас там такой код:
---
/datum/objective/cult/survive/check_completion()
	var/acolytes_survived = 0
	if(!GLOB.cult)
		return 0
	for(var/datum/mind/cult_mind in GLOB.cult.current_antagonists)
		if (cult_mind.current && cult_mind.current.stat!=2)
			var/area/A = get_area(cult_mind.current )
			if ( is_type_in_list(A, GLOB.using_map.post_round_safe_areas))
				acolytes_survived++
	if(acolytes_survived >= target_amount)
		return 0
	else
		return 1
---
Я предлагаю его заменить на нечто следующего формата:
/datum/objective/cult/survive/check_completion()
	var/acolytes_survived = 0
	if (!GLOB.cult)
		return 0
	var/area/shuttle = locate(/area/shuttle/escape/centcom)
	for (var/datum/mind/cult_mind in GLOB.cult.current_antagonists)
		if (cult_mind.current && cult_mind.current.stat!=2)
			if (get_turf(cult_mind.current) in shuttle)
				acolytes_survived++
	if (acolytes_survived >= target_amount)
		return 1
	return 0
---
И читать приятнее, и работать будет.
Опционально можно вызвать проверку, как в datum/objective/block, на то, отлетел ли, собственно, шатол. но зачем.

**Comment by Rodial-Admiral** [comment]
Кря, у меня что-то с форматированием.
Но главное - суть.

**Comment by Rodial-Admiral** [comment]
```/datum/objective/cult/survive/check_completion()
var/acolytes_survived = 0
if (!GLOB.cult)
    return 0
var/area/shuttle = locate(/area/shuttle/escape/centcom)
for (var/datum/mind/cult_mind in GLOB.cult.current_antagonists)
    if (cult_mind.current && cult_mind.current.stat!=2)
        if (get_turf(cult_mind.current) in shuttle)
            acolytes_survived++
if (acolytes_survived >= target_amount)
    return 1
return 0

**Comment by Rodial-Admiral** [comment]
Да куда строчки делись. Минуточку.

**Comment by Rodial-Admiral** [comment]
Давно на гитхабе не сидел, что-то идет не так.

**Comment by Rodial-Admiral** [comment]
А, разобрался. В общем, ждем Эпикуса.

**Comment by Rodial-Admiral** [comment]
Хотя, я так посмотрел, пост_раунд_сейф_эреас тоже можно использовать, но по мне так во избежание технических ошибок и во имя оптимизации лучше смотреть на тех культистов, которые находились на шаттле и не были мертвы в момент проверки.

**Comment by Rodial-Admiral** [comment]
Я вам даже код скинул, а никто так и не пощупал.
Неужто мне придется это дело заливать? Жуть какая.

**Comment by Rodial-Admiral** [comment]
Я вам там залил ПР по этому делу
И, как выяснилось, тут еще нет GLOB-ов на антагах, в отличие от Бея
