### ISSUE TITLE
Нада две лампочки в медбей впендюрить

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#31]
В лобби медбея, прямо на ресепшене, потерялись две лампочки, из-за чего там темно.
Их нужно было бы поставить возле виндуров.

**Comment by ITCups** [comment]
Починил вместе с новым роботехом

**Comment by Epicus7** [comment]
Здесь должно быть пофикшено уже: 72ef08d2e4e3b95ebe0931faa2efa763f54d6ae0
