### ISSUE TITLE
Вирус грейтайда (ивент) открывает не весь бриг

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#32]
А должен еще открыть четыре шлюза, ведущих внутрь из лобби.

А должен еще открыть шлюз, ведущий из техов в медуголок брига. Причем один шлюз туда открывается, что ведёт ПРЯМО (Security Maintenance) в медуголок, а второй (Maintenance Access), в техи - нет. Что имеет сомнительный функциональный смысл для заключенных.

**Comment by Epicus7** [comment]
Какой-какой ивент? Серьезно?

**Comment by Kapitolina** [comment]
Prison break
