### ISSUE TITLE
В админ панели спрятался (Force Secret Mode), пока игра в лобби.

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#35]
(Force Secret Mode) появляется в гейм панели только после запуска раунда, что, внезапно, лишает эту кнопку всякого функционала.

**Comment by Epicus7** [comment]
Система выбора режима была перепилена в коммите c9fc8b53774207261739aa5c0199f23530744b35.

После этих изменений баг не воспроизводится.
