### ISSUE TITLE
Высокое давление где-то в бриге

### ISSUE THREAD

**Issue by vaserg** [Rampoch/Chaotic-Onyx#36]
#### Описание проблемы
Каждый раунд, когда какой-нибудь СБ-шник открывает оружейку, появляется каскад атмосферных тревог, сигнализирующих о высоком давлении. Начинается всё с оружейки, заканчивается, в большинстве случаев, в кабинете Вардена. Оно ещё повышается с течением раунда.

#### Разница между реальным поведением и ожидаемым
Очевидно, давление просто так там повышаться не должно.

#### Как воспроизвести проблему?
Точно не знаю, связано ли это с установкой высокого давления в синих воздуховодных трубах атмоса, но, примерно через полтора часа раунда в оружейке давление под 200 килоПаскаль

#### Конкретная информация

Никакой конкретной информации нет, разве что, аналогичная ситуация была с ксенобиологией, где были похерены трубы. Возможно в оружейке тоже с ними траблы.

#### Как долго известно о проблеме?

С установки новобея.

#### Дополнительная информация

- [x] Проблему можно воспроизвести хотя бы один раз
- [x] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [x] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [x] Проблема случилась в недавнем раунде (прошло меньше недели)
- [x] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by vaserg** [comment]
Так и есть, в оружейке не хватает пары труб. Если поснимать плитку, видим вот такую картину:
![bug](https://user-images.githubusercontent.com/28756259/37554702-93aeb1ba-29ed-11e8-83c0-904f3b512832.png)

**Comment by Epicus7** [comment]
Отлично, спасибо за скрин. Уж 2 трубы поставить это совсем изи - сделаем
