### ISSUE TITLE
Может убрать киборгизированных людей?

### ISSUE THREAD

**Issue by Voldirs** [Rampoch/Chaotic-Onyx#44]
Они какие-то дохера имбовые. У них только одна уязвимость и это ЭМИ. Но на станции очень мало источников ЭМИ.

**Comment by Epicus7** [comment]
Это киберлюди, которые из Доктора Кто что ли?

Мы их, наверное, запилим как отдельный ивент, но сначала надо пофиксить #63

**Comment by Epicus7** [comment]
Все расы, кроме трех стандартных выпилены. Будем добавлять их назад по мере придумывания предыстории под них.
