### ISSUE TITLE
Алкоголь убивает с трех глотков

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#50]
Говорят прям серьезно убивает, минус почки после трех глотков.

Надо проверить и починить, если это действительно так.

**Comment by Voldirs** [comment]
Вообще не правда. Нет, если они конечно пьют водку или что-то крепкое из стаканов, то да, такое возможно, но я сам тестил это дело и могу сказать точно, что от алкоголя подохнуть на этом билде можно, но это надо постараться

**Comment by ITCups** [comment]
Не могу воспроизвести, возможно в алкоголь подмешали токсинов ?
