### ISSUE TITLE
Выпилить Ghost для живых персонажей

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#51]
Им слишком часто злоупотребляют, в то время как ситуации, для которых он, действительно, нужен, встречаются совсем редко.

**Comment by Voldirs** [comment]
А что случилось то? Фича как фича. Если ты про то, что можно зайти каким-нибудь ЕРТшником сразу после выхода из тела, то да, там надо ставить ограничение в 5 минут как на блубэе.

**Comment by Epicus7** [comment]
Выходят из тела во время игровых ситуаций. Раненые сразу после взрыва, заключенные, которых посадили на 10 минут, заложники, которых оставили на 2 минуты связанными на стуле и т.д.

**Comment by Kapitolina** [comment]
Ограничения не сделают людей из обезьян, бесполезная идея. Только нельзя будет гостануться, если тебя закрыли/сломали ноги/кинули в космос. Надо ждать рестарт или пока что-то не убьет.

**Comment by Epicus7** [comment]
Хорошо, что я не дрессировщик обезьян. Меня больше волнуют не сами обезьяны, а те, кого лишают геймплея: врачей, инженеров и СБ. Игроки часто злоупотребляют возможностью выйти из тела, что лишает какого-либо смысла любые попытки их спасать. Очень весело вытащить персонажа из космоса или пожара, а потом узнать, что он тупое бревно.

Всякие любители выйти из тела, когда их посадили на 10 минут, тоже не нужны.

Единственная проблема, которая решается Ghost'ом - это когда тебя реально загрифонили, бросив здоровым в закрытом карцере. И то далеко не всегда ясно, собирается ли персонаж вернуться через пару минут, а ведь если он вернется, то это уже игровая ситуация, а не гриф. Реальные ситуации с подобным грифом встречаются довольно редко и их можно решать через АХ.
