### ISSUE TITLE
Ксеносы

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#54]
1. Посмотреть что там со спрайтами ксеносов и их одеждой (#63)
2. Проставить правильные ограничения по профессиям для ксеносов.
3. Вернуть их в игру

**Comment by Voldirs** [comment]
Может всё таки сначала сделать им несколько бОльшие отличия, некоторые нерфы по сравнению с тем, что есть сейчас? Напомню, бэйцы тем же ящерам дали возможность отращивать конечности и вроде даже органы за счёт нутриментов. Только нутриментов ящерам нужно больше. Просто на данный момент, ксеносы это бафнутые респрайты людей (за исключением скреллов). Я вообще не понимаю зачем их возвращать нужно в таком виде, и так замечательно играется.

**Comment by Epicus7** [comment]
Связано с #63

**Comment by Epicus7** [comment]
Ограничения поставил, ксеносов в игру вернул: 0332844fbc84237b91f4aaab239b78763d8a56d6
