### ISSUE TITLE
Отодвинуть паникбункер на кнопку Join Game

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#55]
Сейчас паникбункер молча рубит коннекшен всем игрокам, которые раньше не заходили на сервер.

Идеально было бы перенести этот фильтр на кнопку Join Game, чтобы новички могли просить доступ прямо на сервере у педалей из лобби.

**Comment by bombanyTI** [comment]
Новичок может и в дискорде попросить, перепил паникбункера вижу бессмысленым

**Comment by Epicus7** [comment]
Ссылка на дискорд-канал есть только на сервере, а найти информацию о том, куда писать немного проблематично может быть для нового игрока, тем более с другого сервера.

И мы уже придумали способ в принципе отказаться от паник-бункера за счет ужесточения контроля данных о подключении игрока. Этот способ должен помочь нам избавиться от мультиакков, не ограничивая новых игроков.

**Comment by Epicus7** [comment]
Решили выпилить паникбункер, заменив его EAMS.
