### ISSUE TITLE
Выпилить малфа из ротации, ибо режим сырой

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#65]
У малфа нет нормальных кнопок, чтобы этот режим был = ниндже или магу. Причем последние и то часто идут вкупе с триторами, а малф - нет. Что вкупе со скудностью его функционала - лишено всякого смысла. Трейторки на ИИ более чем хватает, чтобы игрок спокойно мог реализовать свои идеи.

**Comment by Arvard** [comment]
За малфа играть просто не умеют. Вот и всё. Я пока не видел еще ни одной грамотной игры за малфа. Тут способов полно если включить воображение и немного подумать. Один атмос чего стоит. Достаточно нагреть воздух, да посильнее и пустить его в трубы. Никакие скафандры и противогазы людей не спасут, за исключением конкретно ригов, если до них доберутся. А если в запасе есть пара боргов, то всё в разы упрощается.

**Comment by Epicus7** [comment]
Интересно еще то, что ИИ может выпилить весь персонал на станции и играть соло еще час после этого.

Условия режима, конечно, надо перерабатывать. Насчет ротации - не знаю. Во-первых, тут скорее всего, надо в конфиги лезть. Во-вторых, если убрать ИИ, то вылезет другой режим, который всем будет не нравится. Там надо в целом смотреть и решать какая ротация должна быть.

**Comment by Epicus7** [comment]
Обновили ротацию карты. У Малфа теперь пониженный приоритет - вероятность его прока должна быть довольно мала, учитывая обилие других режимов.

**Comment by Epicus7** [comment]
На малфа никто больше не жалуется, потому что появляется он крайне редко. На крайняк, можно отключить через конфиг.
