### ISSUE TITLE
Инженерный аванпост требует мапских фиксов: зона, стыковка и перестановка кнопочки.

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#71]
1. В туалете нет ни зоны, ни АПЦ.
2. Шаттл не состыковывается с аванпостом - шлюзы аванпоста не открываются.
3. Кнопочка exterior висит странно. Разве с шаттла её должно мочь ткнуть? Только с космоса?

**Comment by ghost** [comment]
Всё исправлено вот здесь:
0e2d436112b582763bcded1f436f8f0c79ece402
