### ISSUE TITLE
Ребаланс оружия

### ISSUE THREAD

**Issue by Pro100Nikit** [Rampoch/Chaotic-Onyx#82]
На данный момент летальное оружие обладает практически нулевым останавливающим действием. Достаточно добавить агонии и уже будет лучше.

**Comment by Epicus7** [comment]
Началось...

>Ребаланс
Это так не делается. Нужно системно смотреть все оружие, которое есть в игре + медицину и думать. Рандомно поднимать/опускать характеристики у разных предметов по ощущениям разных игроков - такое себе.

**Comment by Epicus7** [comment]
Слишком размытый иссуи, тут непонятно что делать совсем.
