### ISSUE TITLE
Саплай маяк вызывает ящик с каким-то мусором

### ISSUE THREAD

**Issue by Epicus7** [Rampoch/Chaotic-Onyx#87]
> [14:51] Pro100Nikit: Покупаем в аплинке саплай маяк - ставим его на провод - активируем - ждем минуту - все получают оповещение с координатами куда доставляется баллистическое снаряжение - прилетает под который сносит пол отсека - А ВНУТРИ ГЕНЕРАТОР ПАКМАН

Внутри должно быть что-то имбовое, очевидно.

**Comment by Pro100Nikit** [comment]
Как удалось выяснить выбирается рандомный пак из возможных. Может прилететь суперматерия. По задумке должен прилетать ящик с баллистическим снаряжением.

**Comment by Epicus7** [comment]
Надо посмотреть список того, что может прилететь и с какими вероятностями.

**Comment by Voldirs** [comment]
Читаем текст внимательнее, там написано не про баллистическое снаряжение, а про баллистическую доставку. И судя по коду, в суплае может быть довольно большой список зачастую бесполезных вещей
https://github.com/Baystation12/Baystation12/blob/0ab4e16d9448fed066b5017cd98edb4c3d8281dc/code/modules/random_map/drop/drop_types.dm
